const studentData = [
  {
    name: "Alice Johnson",
    studentID: "202100001",
    section: "A",
    department: "Computer Science",
    email: "alice.johnson@example.com",
    password: "hashedPassword1",
    gender: "Female",
    role: "Student",
    age: 20,
    mobile: 1234567890,
    year: 2,
  },
  {
    name: "Bob Williams",
    studentID: "202100002",
    section: "B",
    department: "Electrical Engineering",
    email: "bob.williams@example.com",
    password: "hashedPassword2",
    gender: "Male",
    role: "Student",
    age: 21,
    mobile: 9876543210,
    year: 3,
  },
  {
    name: "Eva Davis",
    studentID: "202100003",
    section: "C",
    department: "Mechanical Engineering",
    email: "eva.davis@example.com",
    password: "hashedPassword3",
    gender: "Female",
    role: "Student",
    age: 19,
    mobile: 5555555555,
    year: 1,
  },
  {
    name: "Charlie Brown",
    studentID: "202100004",
    section: "A",
    department: "Civil Engineering",
    email: "charlie.brown@example.com",
    password: "hashedPassword4",
    gender: "Male",
    role: "Student",
    age: 22,
    mobile: 1111222233,
    year: 4,
  },
  {
    name: "Grace Smith",
    studentID: "202100005",
    section: "B",
    department: "Chemical Engineering",
    email: "grace.smith@example.com",
    password: "hashedPassword5",
    gender: "Female",
    role: "Student",
    age: 20,
    mobile: 9998887777,
    year: 2,
  },
  {
    name: "David Lee",
    studentID: "202100006",
    section: "C",
    department: "Physics",
    email: "david.lee@example.com",
    password: "hashedPassword6",
    gender: "Male",
    role: "Student",
    age: 23,
    mobile: 4444333322,
    year: 3,
  },
  {
    name: "Sophia Miller",
    studentID: "202100007",
    section: "A",
    department: "Mathematics",
    email: "sophia.miller@example.com",
    password: "hashedPassword7",
    gender: "Female",
    role: "Student",
    age: 21,
    mobile: 6666777788,
    year: 2,
  },
  {
    name: "Jack Robinson",
    studentID: "202100008",
    section: "B",
    department: "Computer Engineering",
    email: "jack.robinson@example.com",
    password: "hashedPassword8",
    gender: "Male",
    role: "Student",
    age: 24,
    mobile: 1212121212,
    year: 4,
  },
  {
    name: "Olivia Turner",
    studentID: "202100009",
    section: "C",
    department: "Biology",
    email: "olivia.turner@example.com",
    password: "hashedPassword9",
    gender: "Female",
    role: "Student",
    age: 19,
    mobile: 9898989898,
    year: 1,
  },
  {
    name: "William Harris",
    studentID: "202100010",
    section: "A",
    department: "Chemistry",
    email: "william.harris@example.com",
    password: "hashedPassword10",
    gender: "Male",
    role: "Student",
    age: 22,
    mobile: 7878787878,
    year: 3,
  },
];

module.exports = studentData;
