export const TaskData = [
    {
        id: 1,
        status: 'To Do',
        summary: 'Analyze the new requirements gathered from the customer.',
        Type: 'Task',
        Priority: 'Low',
        Tags: 'Analyze,Customer',
        date: 3.5,
        Assigned: 'Nancy Davloio',
        Rankid: 1,
        Tags: 'Analyze,Customer'
    },
    {
        id: 2,
        status: 'In Progress',
        summary: 'Improve application performance',
        Type: 'Bug',
        Priority: 'Critical',
        Tags: 'Improvement',
        date: 6,
        Assigned: 'Andrew Fuller',
        Rankid: 2,
        Tags: 'Improvement'
    },
    {
        id: 3,
        status: 'Testing',
        summary: 'Develop the unit test cases for the developed modules.',
        Type: 'Story',
        Priority: 'High',
        Tags: 'Testing,Modules',
        date: 5.5,
        Assigned: 'Janet Leverling',
        Rankid: 3,
        Tags: 'Testing,Modules'
    },
    {
        id: 4,
        status: 'Done',
        summary: 'Prepare the project plan',
        Type: 'Story',
        Priority: 'High',
        Tags: 'Plan',
        date: 3.5,
        Assigned: 'Janet Leverling',
        Rankid: 4,
        Tags: 'Plan'
    },
    {
        id: 5,
        status: 'To Do',
        summary: 'Customer details are not available',
        Type: 'Bug',
        Priority: 'Low',
        Tags: 'Customer',
        date: 3.5,
        Assigned: 'Steven walker',
        Rankid: 1,
        Tags: 'Customer'
    },
    {
        id: 6,
        status: 'In Progress',
        summary: 'Development of the customer support module.',
        Type: 'Story',
        Priority: 'Critical',
        Tags: 'Development,Support',
        date: 6,
        Assigned: 'Margaret hamilt',
        Rankid: 2,
        Tags: 'Development,Support'
    },
    {
        id: 7,
        status: 'Testing',
        summary: 'Customer feedback report analysis',
        Type: 'Story',
        Priority: 'Normal',
        Tags: 'Customer,Feedback',
        date: 5.5,
        Assigned: 'Steven walker',
        Rankid: 3,
        Tags: 'Customer,Feedback'
    }]