const teacherData = [
  {
    type: "teacher",
    name: "Alice Johnson",
    email: "alice.johnson@email.com",
    courses: [],
    password: "hashedPassword1",
    gender: "Female",
    age: 35,
    isAdmin: false,
    mobile: 1234567890,
  },
  {
    type: "teacher",
    name: "Bob Williams",
    email: "bob.williams@email.com",
    courses: [],
    password: "hashedPassword2",
    gender: "Male",
    age: 40,
    isAdmin: true,
    mobile: 9876543210,
  },
  {
    type: "teacher",
    name: "Eva Davis",
    email: "eva.davis@email.com",
    courses: [],
    password: "hashedPassword3",
    gender: "Female",
    age: 28,
    isAdmin: false,
    mobile: 5555555555,
  },
  {
    type: "teacher",
    name: "Charlie Brown",
    email: "charlie.brown@email.com",
    courses: [],
    password: "hashedPassword4",
    gender: "Male",
    age: 32,
    isAdmin: false,
    mobile: 1111222233,
  },
  {
    type: "teacher",
    name: "Grace Smith",
    email: "grace.smith@email.com",
    courses: [],
    password: "hashedPassword5",
    gender: "Female",
    age: 25,
    isAdmin: false,
    mobile: 9998887777,
  },
  {
    type: "teacher",
    name: "David Lee",
    email: "david.lee@email.com",
    courses: [],
    password: "hashedPassword6",
    gender: "Male",
    age: 45,
    isAdmin: true,
    mobile: 4444333322,
  },
  {
    type: "teacher",
    name: "Sophia Miller",
    email: "sophia.miller@email.com",
    courses: [],
    password: "hashedPassword7",
    gender: "Female",
    age: 30,
    isAdmin: false,
    mobile: 6666777788,
  },
  {
    type: "teacher",
    name: "Jack Robinson",
    email: "jack.robinson@email.com",
    courses: [],
    password: "hashedPassword8",
    gender: "Male",
    age: 38,
    isAdmin: false,
    mobile: 1212121212,
  },
  {
    type: "teacher",
    name: "Olivia Turner",
    email: "olivia.turner@email.com",
    courses: [],
    password: "hashedPassword9",
    gender: "Female",
    age: 33,
    isAdmin: false,
    mobile: 9898989898,
  },
  {
    type: "teacher",
    name: "William Harris",
    email: "william.harris@email.com",
    courses: [],
    password: "hashedPassword10",
    gender: "Male",
    age: 29,
    isAdmin: false,
    mobile: 7878787878,
  },
];

module.exports = teacherData;
